### ISSUE TITLE
Level initialization seems to be incorrect

### ISSUE THREAD

**Issue by cybo0001** [morno/DingClassic#5]
Started using the addon at level 13, near the end of the level. After messing with some settings, I kill a mob and it immediately reports a ding when there wasn't one. Killed a few more mobs, dinged 14, and no announcement was made.

My only assumption scanning through the code is that level initialization isn't correct, but you'd know better than I. I wasn't running debug mode at the time.

Is it possible that part of messing with the settings i.e. sending 'test' messages, it messes with your checks to see if a message has been fired this level etc and things get out of sync?

**Comment by cybo0001** [comment]
Running the addon on a level 60 character, it randomly at some point decided to announce a ding after a quest turn in I believe, even though I'm already at level cap.

**Comment by morno** [comment]
Hello

i have also notice these issues i have updated the addon to make the debug and update easyer.. i am testing the new version. if its stable i will upload it to Curse and here :)

**Comment by morno** [comment]
Hello

i have now reworked the addon to hopefully work better and added new feature like Locales, a test function to test the ding function and a better debug and hopefully better to work with in the furure.

See https://github.com/morno/DingClassic/releases/tag/v1.0.11 or wait until the addon gets approved by curse :)
